### PR TITLE
build: switch to bun for dep management

### PR DESCRIPTION
**Pull request by PaulRBerg**

### CODE REVIEW

**Comment by pegahcarter** [comment]
Is this the move for foundry projects now?

**Comment by PaulRBerg** [comment]
It's my move.

https://x.com/paulrberg/status/1736694426578137247?s=46

**Comment by pegahcarter** [comment]
tbh I got my team to switch to pnpm after seeing you use it here.  I'm guessing the switch to bun is to avoid node.js install entirely?

**Comment by PaulRBerg** [comment]
Oh, I see. I documented the rationale for moving away from PNPM here:

https://github.com/ethereum/go-ethereum/issues/20193#issuecomment-649401055

**Pull request merged**
