### PR TITLE
Slightly gas saving in avg function

### PR DESCRIPTION
**Pull request by Atarpara**
I remove the unnecessary operation in avg function.

### CODE REVIEW

**Comment by paulrberg** [comment]
Hi @Atarpara! Thanks for your contribution. Unfortunately, I cannot merge this. In fact, I cannot even review it:

- The code does not compile, it fails with the error "ParserError: Expected ';' but got '}'"
- The linter job does not pass (see CI logs) (make sure to install the [Prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) for VSCode)
- This PR does not include an explanation for why the proposed change brings about a reduction in gas costs *while* simultaneously keeping the behavior of the `avg` function the same across all possible inputs and outputs

**Comment by Atarpara** [comment]
@paulrberg I solved the compiler error.

**Comment by paulrberg** [comment]
Hi @Atarpara, thanks for that. Would you mind explaining how your gas saving works?

**Comment by Atarpara** [comment]
Reduce the Number of Operation 

Old Way: `(x >> 1) + (y >> 1) + (x & y & 1)` - Need 6 Operation

New Way :  `(x & y) + ((x^y) >> 1)` - Need 4 Operation

**Comment by paulrberg** [comment]
Hello @Atarpara, I'm sorry for the delayed response.

I ran a few tests and indeed you are right - your approach is faster than mine.

Happy to accept this PR, but could I kindly ask you to re-apply your changes onto the tip of the [`staging`](https://github.com/paulrberg/prb-math/tree/staging) branch, git push with force to your branch, and then make `staging` the base of this PR?

Thank you!

**Comment by paulrberg** [comment]
Hi @Atarpara, I'm sorry, I accidentally closed your PR.

But I managed to implement your proposal, and credit you as a git author in commit https://github.com/paulrberg/prb-math/commit/a490c088c5de0564d48064b0c2a0647ab9d4299c.

Thanks again for your contribution.

**Pull request closed without merging**
