### PR TITLE
refactor: remove adjacent castings

### LINKED ISSUE #236: Remove casting functions between the adjacent types
While reviewing #212, I realized that maintaining casting functions between the adjacent types and all other types is:

1. Overkill and not helpful; I don't think users need this.
2. Increasing maintenance costs in an exponential way; the more adjacent types there are, the crazier the interdependencies become, and the more 'plumbing' code has to be written.

Thus, the task is to remove all casting functions between the adjacent types and all other types, e.g. between SD1x18 and UD2x18.

Note that the casting between (i) adjacent types and SD59x18 and UD60x18 and (ii) between SD59x18 and UD60x18 should continue to be maintained given that these are the core types implementing the mathematical logic.

### PR DESCRIPTION
**Pull request by PaulRBerg**
Closes #236

### CODE REVIEW

**Comment by PaulRBerg** [comment]
@andreivladbrg @smol-ninja could you PTAL to check if this PR doesn't break Flow?

**Comment by andreivladbrg** [comment]
> @andreivladbrg @smol-ninja could you PTAL to check if this PR doesn't break Flow?

As far as I can see, the changes made in this PR are related to the casting function and not specifically to the newly added types. Therefore, I don’t see any issues that would cause a break in `Flow`

**Comment by PaulRBerg** [comment]
Well, the PR is related to the new types insofar it removes some of their functionalities.

can you please install PRBMath from this branch and confirm that the code still compiles?

**Comment by andreivladbrg** [comment]
`Flow` doesn't use `UD21x18` yet, since the PR just got merged, we are about make the change.

But, I've tested from [this commit](https://github.com/sablier-labs/flow/commit/8c77338045e18b858ee597ac90fca0ef460c3461), and the [build runs](https://app.warp.dev/block/C5vQgWVDqXRJk6izm20PpE).

**Comment by PaulRBerg** [comment]
Thanks @andreivladbrg.

**Pull request merged**
